import groovy.sql.Sql
import groovy.sql.examples.GroovySqlHandler

Sql sql = GroovySqlHandler.createDriverManagerSql()

sql.execute """
    DROP INDEX cityIdx IF EXISTS;
    DROP TABLE city IF EXISTS;

    CREATE TABLE city (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY,
        name VARCHAR(64),
        state VARCHAR(64),
        founded_year INTEGER(4)
    );

    CREATE INDEX cityIdx ON city (id);
"""